import { Wallet, Currency, CurrencyRegion, Transaction, RateStats, YieldInfo } from './types';

// ---------------------------------------------------------------------------
// Testnet Configuration
// ---------------------------------------------------------------------------
export const RPC_URL = process.env.NEXT_PUBLIC_RPC_URL || 'http://35.184.213.248:8545';
export const REST_URL = process.env.NEXT_PUBLIC_REST_URL || 'http://35.184.213.248:8080';
export const CHAIN_ID = 'dina-testnet-1';

// ---------------------------------------------------------------------------
// Mock Wallets
// ---------------------------------------------------------------------------
const NOW = Math.floor(Date.now() / 1000);
const ONE_HOUR_AGO = NOW - 3600;
const ONE_DAY_AGO = NOW - 86400;
const THREE_DAYS_AGO = NOW - 259200;

export const MOCK_WALLETS: Wallet[] = [
  {
    id: 'main-1',
    name: 'Main Wallet',
    type: 'main',
    icon: '🏦',
    balance: 2_347_530_000,
    yieldRateBps: 450,
    lastYieldUpdate: ONE_HOUR_AGO,
    isDefault: true,
    isSetUp: true,
  },
  {
    id: 'savings-1',
    name: 'Savings',
    type: 'savings',
    icon: '🐷',
    balance: 10_000_000_000,
    yieldRateBps: 500,
    lastYieldUpdate: ONE_HOUR_AGO,
    isSetUp: true,
  },
  {
    id: 'backup-1',
    name: 'Backup',
    type: 'backup',
    icon: '🔒',
    balance: 500_000_000,
    yieldRateBps: 450,
    lastYieldUpdate: ONE_HOUR_AGO,
    isSetUp: true,
  },
  {
    id: 'agent-1',
    name: 'Shopping',
    type: 'agent',
    icon: '🛒',
    balance: 150_000_000,
    yieldRateBps: 350,
    lastYieldUpdate: ONE_HOUR_AGO,
    dailyLimit: 500_000_000,
    isSetUp: true,
  },
  {
    id: 'agent-2',
    name: 'Bills',
    type: 'agent',
    icon: '📄',
    balance: 50_000_000,
    yieldRateBps: 350,
    lastYieldUpdate: ONE_HOUR_AGO,
    dailyLimit: 200_000_000,
    isSetUp: true,
  },
  {
    id: 'agent-3',
    name: 'Agent 3',
    type: 'agent',
    icon: '🤖',
    balance: 0,
    yieldRateBps: 350,
    lastYieldUpdate: NOW,
    isSetUp: false,
  },
  {
    id: 'speed-1',
    name: 'Business',
    type: 'speed',
    icon: '⚡',
    balance: 100_000_000,
    yieldRateBps: 300,
    lastYieldUpdate: ONE_HOUR_AGO,
    isSetUp: true,
  },
  {
    id: 'speed-2',
    name: 'Speed 2',
    type: 'speed',
    icon: '⚡',
    balance: 0,
    yieldRateBps: 300,
    lastYieldUpdate: NOW,
    isSetUp: false,
  },
  {
    id: 'speed-3',
    name: 'Speed 3',
    type: 'speed',
    icon: '⚡',
    balance: 0,
    yieldRateBps: 300,
    lastYieldUpdate: NOW,
    isSetUp: false,
  },
];

// ---------------------------------------------------------------------------
// All 155 Deployed Currencies (from deploy-all-currencies.js)
// Rates are micro-units per 1 USDC (6 decimals). e.g. EUR at 0.93 = 930_000
// Yield rates in basis points (450 = 4.50% APY)
//
// Generated by: node scripts/deploy-all-currencies.js
// Source JSON:   wallet-app/src/lib/currencies.json
// ---------------------------------------------------------------------------
import deployedCurrencies from './currencies.json';

// Country code -> region mapping for display grouping
const COUNTRY_REGION_MAP: Record<string, CurrencyRegion> = {
  // Major (top-level global reserve currencies get special grouping)
  US: 'Major', EU: 'Major', GB: 'Major', JP: 'Major', CH: 'Major', AU: 'Major', CA: 'Major', CN: 'Major',
  // North America
  MX: 'North America', GT: 'North America', BZ: 'North America', HN: 'North America', NI: 'North America',
  CR: 'North America', PA: 'North America', DO: 'North America', CU: 'North America', HT: 'North America',
  JM: 'North America', TT: 'North America', BB: 'North America', BS: 'North America', EC: 'North America',
  AW: 'North America', CW: 'North America', BM: 'North America', KY: 'North America',
  // South America
  BR: 'South America', AR: 'South America', CL: 'South America', CO: 'South America', PE: 'South America',
  UY: 'South America', PY: 'South America', BO: 'South America', VE: 'South America', GY: 'South America',
  SR: 'South America', FK: 'South America',
  // Western Europe
  SE: 'Western Europe', NO: 'Western Europe', DK: 'Western Europe', IS: 'Western Europe', GI: 'Western Europe',
  // Eastern Europe
  PL: 'Eastern Europe', CZ: 'Eastern Europe', HU: 'Eastern Europe', RO: 'Eastern Europe', BG: 'Eastern Europe',
  HR: 'Eastern Europe', RS: 'Eastern Europe', BA: 'Eastern Europe', MK: 'Eastern Europe', AL: 'Eastern Europe',
  MD: 'Eastern Europe', UA: 'Eastern Europe', BY: 'Eastern Europe', GE: 'Eastern Europe', AM: 'Eastern Europe',
  AZ: 'Eastern Europe', TR: 'Eastern Europe', RU: 'Eastern Europe',
  // East Asia
  TW: 'East Asia', HK: 'East Asia', MO: 'East Asia', MN: 'East Asia', KP: 'East Asia', KR: 'East Asia',
  // Southeast Asia
  SG: 'Southeast Asia', TH: 'Southeast Asia', MY: 'Southeast Asia', ID: 'Southeast Asia', PH: 'Southeast Asia',
  VN: 'Southeast Asia', MM: 'Southeast Asia', KH: 'Southeast Asia', LA: 'Southeast Asia', BN: 'Southeast Asia',
  TL: 'Southeast Asia',
  // South Asia
  IN: 'South Asia', PK: 'South Asia', BD: 'South Asia', LK: 'South Asia', NP: 'South Asia',
  BT: 'South Asia', MV: 'South Asia', AF: 'South Asia',
  // Middle East
  AE: 'Middle East', SA: 'Middle East', QA: 'Middle East', BH: 'Middle East', OM: 'Middle East',
  KW: 'Middle East', JO: 'Middle East', IL: 'Middle East', LB: 'Middle East', IQ: 'Middle East',
  IR: 'Middle East', SY: 'Middle East', YE: 'Middle East',
  // Central Asia
  KZ: 'Central Asia', UZ: 'Central Asia', KG: 'Central Asia', TJ: 'Central Asia', TM: 'Central Asia',
  // North Africa
  EG: 'North Africa', MA: 'North Africa', DZ: 'North Africa', TN: 'North Africa', LY: 'North Africa', SD: 'North Africa',
  // West Africa
  NG: 'West Africa', GH: 'West Africa', WA: 'West Africa', GM: 'West Africa', GN: 'West Africa',
  SL: 'West Africa', LR: 'West Africa', CV: 'West Africa', MR: 'West Africa',
  // East Africa
  KE: 'East Africa', TZ: 'East Africa', UG: 'East Africa', ET: 'East Africa', RW: 'East Africa',
  BI: 'East Africa', SO: 'East Africa', DJ: 'East Africa', ER: 'East Africa', SS: 'East Africa',
  // Central Africa (XAF uses 'CA' country code which collides with Canada — handled below)
  CD: 'Central Africa', ST: 'Central Africa',
  // Southern Africa
  ZA: 'Southern Africa', BW: 'Southern Africa', NA: 'Southern Africa', SZ: 'Southern Africa',
  LS: 'Southern Africa', MW: 'Southern Africa', ZM: 'Southern Africa', MZ: 'Southern Africa',
  AO: 'Southern Africa', MG: 'Southern Africa', MU: 'Southern Africa', SC: 'Southern Africa',
  KM: 'Southern Africa', ZW: 'Southern Africa',
  // Oceania
  NZ: 'Oceania', FJ: 'Oceania', PG: 'Oceania', WS: 'Oceania', TO: 'Oceania',
  VU: 'Oceania', SB: 'Oceania', PF: 'Oceania',
};

// Special override: XAF's country is 'CA' (Central Africa) which collides with Canada
function getRegion(code: string, country: string): CurrencyRegion {
  if (code === 'XAF') return 'Central Africa';
  return COUNTRY_REGION_MAP[country] || 'Middle East & Africa';
}

// Build the full currency list from deployed data + USDC as native
export const MOCK_CURRENCIES: Currency[] = [
  // USDC is native — not in the deployed JSON
  { symbol: 'USDC', name: 'US Dollar', balance: 12_947_530_000, yieldRateBps: 450, ratePerUsdc: 1_000_000, icon: '\u{1F1FA}\u{1F1F8}', region: 'Major' },
  // All 154 deployed stablecoins
  ...deployedCurrencies.map((c: { symbol: string; name: string; yield: number; rate: number; flag: string; code: string; country: string }) => ({
    symbol: c.symbol,
    name: c.name,
    balance: 0,
    yieldRateBps: c.yield,
    ratePerUsdc: c.rate,
    icon: c.flag,
    region: getRegion(c.code, c.country),
  })),
];

// ---------------------------------------------------------------------------
// Currency region order for display grouping
// ---------------------------------------------------------------------------
export const CURRENCY_REGIONS = [
  'Major',
  'North America',
  'South America',
  'Western Europe',
  'Eastern Europe',
  'East Asia',
  'Southeast Asia',
  'South Asia',
  'Middle East',
  'Central Asia',
  'North Africa',
  'West Africa',
  'East Africa',
  'Central Africa',
  'Southern Africa',
  'Oceania',
] as const;

// ---------------------------------------------------------------------------
// Mock Transactions
// ---------------------------------------------------------------------------
export const MOCK_TRANSACTIONS: Transaction[] = [
  { id: 'tx-1', type: 'receive', amount: 500_000_000, currency: 'USDC', counterparty: 'alice.dina', timestamp: ONE_HOUR_AGO, status: 'confirmed', wallet: 'Main Wallet' },
  { id: 'tx-2', type: 'send', amount: 25_000_000, currency: 'USDC', counterparty: 'bob@email.com', timestamp: ONE_DAY_AGO, status: 'confirmed', wallet: 'Main Wallet' },
  { id: 'tx-3', type: 'yield', amount: 1_232_000, currency: 'USDC', timestamp: ONE_DAY_AGO, status: 'confirmed', wallet: 'Savings' },
  { id: 'tx-4', type: 'convert', amount: 200_000_000, currency: 'EURC', counterparty: 'USDC -> EURC', timestamp: THREE_DAYS_AGO, status: 'confirmed', wallet: 'Main Wallet' },
  { id: 'tx-5', type: 'send', amount: 75_000_000, currency: 'USDC', counterparty: 'carol.dina', timestamp: THREE_DAYS_AGO, status: 'confirmed', wallet: 'Shopping' },
];

export const MOCK_WALLET_ADDRESS = '0xd1nA...7f3E';
export const MOCK_WALLET_ADDRESS_FULL = '0xd1nA4b2c8E9f0A1B3d5C7e2F4a6D8b0E9c1F3a5D7f3E';

// ---------------------------------------------------------------------------
// Mock Rate Statistics (30-day analytics per currency)
// ---------------------------------------------------------------------------
export const MOCK_RATE_STATS: Record<string, RateStats> = {
  CAD: {
    current: 1_380_000,
    high24h: 1_385_000, low24h: 1_372_000, avg24h: 1_378_000,
    high7d: 1_395_000, low7d: 1_368_000, avg7d: 1_382_000,
    high30d: 1_410_000, low30d: 1_355_000, avg30d: 1_385_000,
    change24hBps: 30, change7dBps: -80, change30dBps: 120,
  },
  EUR: {
    current: 930_000,
    high24h: 935_000, low24h: 926_000, avg24h: 930_000,
    high7d: 942_000, low7d: 920_000, avg7d: 932_000,
    high30d: 950_000, low30d: 915_000, avg30d: 935_000,
    change24hBps: -10, change7dBps: 50, change30dBps: -80,
  },
  GBP: {
    current: 795_000,
    high24h: 800_000, low24h: 790_000, avg24h: 795_000,
    high7d: 808_000, low7d: 785_000, avg7d: 796_000,
    high30d: 815_000, low30d: 778_000, avg30d: 798_000,
    change24hBps: 20, change7dBps: -30, change30dBps: 60,
  },
  JPY: {
    current: 154_000_000,
    high24h: 154_500_000, low24h: 153_200_000, avg24h: 153_800_000,
    high7d: 155_800_000, low7d: 152_500_000, avg7d: 154_000_000,
    high30d: 157_000_000, low30d: 151_000_000, avg30d: 154_200_000,
    change24hBps: 45, change7dBps: -120, change30dBps: 200,
  },
  MXN: {
    current: 17_500_000,
    high24h: 17_600_000, low24h: 17_350_000, avg24h: 17_480_000,
    high7d: 17_800_000, low7d: 17_200_000, avg7d: 17_500_000,
    high30d: 18_100_000, low30d: 17_000_000, avg30d: 17_550_000,
    change24hBps: 50, change7dBps: -150, change30dBps: 300,
  },
  BRL: {
    current: 5_050_000,
    high24h: 5_080_000, low24h: 5_020_000, avg24h: 5_045_000,
    high7d: 5_120_000, low7d: 4_980_000, avg7d: 5_060_000,
    high30d: 5_200_000, low30d: 4_900_000, avg30d: 5_070_000,
    change24hBps: 35, change7dBps: -90, change30dBps: 180,
  },
  INR: {
    current: 83_500_000,
    high24h: 83_700_000, low24h: 83_200_000, avg24h: 83_450_000,
    high7d: 84_000_000, low7d: 83_000_000, avg7d: 83_500_000,
    high30d: 84_500_000, low30d: 82_800_000, avg30d: 83_600_000,
    change24hBps: 15, change7dBps: -40, change30dBps: 90,
  },
  AUD: {
    current: 1_540_000,
    high24h: 1_548_000, low24h: 1_532_000, avg24h: 1_538_000,
    high7d: 1_560_000, low7d: 1_520_000, avg7d: 1_542_000,
    high30d: 1_575_000, low30d: 1_510_000, avg30d: 1_545_000,
    change24hBps: 25, change7dBps: -60, change30dBps: 100,
  },
  CHF: {
    current: 885_000,
    high24h: 890_000, low24h: 880_000, avg24h: 885_000,
    high7d: 895_000, low7d: 878_000, avg7d: 886_000,
    high30d: 900_000, low30d: 870_000, avg30d: 887_000,
    change24hBps: -15, change7dBps: 20, change30dBps: -50,
  },
  KRW: {
    current: 1_340_000_000,
    high24h: 1_345_000_000, low24h: 1_335_000_000, avg24h: 1_339_000_000,
    high7d: 1_355_000_000, low7d: 1_328_000_000, avg7d: 1_342_000_000,
    high30d: 1_370_000_000, low30d: 1_320_000_000, avg30d: 1_345_000_000,
    change24hBps: 20, change7dBps: -70, change30dBps: 150,
  },
  SGD: {
    current: 1_345_000,
    high24h: 1_350_000, low24h: 1_340_000, avg24h: 1_344_000,
    high7d: 1_358_000, low7d: 1_335_000, avg7d: 1_346_000,
    high30d: 1_365_000, low30d: 1_328_000, avg30d: 1_348_000,
    change24hBps: 10, change7dBps: -25, change30dBps: 55,
  },
  NGN: {
    current: 1_550_000_000,
    high24h: 1_560_000_000, low24h: 1_540_000_000, avg24h: 1_548_000_000,
    high7d: 1_580_000_000, low7d: 1_520_000_000, avg7d: 1_555_000_000,
    high30d: 1_620_000_000, low30d: 1_500_000_000, avg30d: 1_560_000_000,
    change24hBps: 60, change7dBps: -200, change30dBps: 450,
  },
  SEK: {
    current: 10_800_000,
    high24h: 10_850_000, low24h: 10_750_000, avg24h: 10_790_000,
    high7d: 10_950_000, low7d: 10_700_000, avg7d: 10_820_000,
    high30d: 11_100_000, low30d: 10_600_000, avg30d: 10_850_000,
    change24hBps: 25, change7dBps: -55, change30dBps: 110,
  },
  PLN: {
    current: 4_050_000,
    high24h: 4_075_000, low24h: 4_025_000, avg24h: 4_048_000,
    high7d: 4_110_000, low7d: 4_000_000, avg7d: 4_060_000,
    high30d: 4_150_000, low30d: 3_950_000, avg30d: 4_065_000,
    change24hBps: 18, change7dBps: -45, change30dBps: 85,
  },
  ZAR: {
    current: 18_200_000,
    high24h: 18_350_000, low24h: 18_050_000, avg24h: 18_180_000,
    high7d: 18_600_000, low7d: 17_900_000, avg7d: 18_250_000,
    high30d: 19_000_000, low30d: 17_500_000, avg30d: 18_300_000,
    change24hBps: 55, change7dBps: -180, change30dBps: 350,
  },
};

// ---------------------------------------------------------------------------
// Mock Yield Positions (user's active currency positions)
// ---------------------------------------------------------------------------
const YIELD_NOW = Math.floor(Date.now() / 1000);
const SEVEN_DAYS_AGO = YIELD_NOW - 7 * 86400;
const FOURTEEN_DAYS_AGO = YIELD_NOW - 14 * 86400;
const THIRTY_DAYS_AGO = YIELD_NOW - 30 * 86400;

export const MOCK_YIELD_POSITIONS: YieldInfo[] = [
  {
    currency: 'CAD',
    currencySymbol: 'C$',
    flag: '\u{1F1E8}\u{1F1E6}',
    localBalance: 1_380_000_000,      // C$1,380.00
    usdcBacking: 1_000_000_000,       // $1,000 USDC
    pendingYieldUsdc: 3_700_000,      // $3.70 USDC
    pendingYieldLocal: 5_106_000,     // C$5.11
    totalClaimedUsdc: 47_200_000,     // $47.20 USDC
    totalClaimedLocal: 65_136_000,    // C$65.14
    depositRate: 1_350_000,           // 1 USDC = 1.350 CAD at deposit
    currentRate: 1_380_000,           // now 1.380
    depositTime: THIRTY_DAYS_AGO,
  },
  {
    currency: 'EUR',
    currencySymbol: '\u20AC',
    flag: '\u{1F1EA}\u{1F1FA}',
    localBalance: 465_000_000,        // EUR 465.00
    usdcBacking: 500_000_000,         // $500 USDC
    pendingYieldUsdc: 1_850_000,      // $1.85 USDC
    pendingYieldLocal: 1_720_500,     // EUR 1.72
    totalClaimedUsdc: 23_400_000,     // $23.40 USDC
    totalClaimedLocal: 21_762_000,    // EUR 21.76
    depositRate: 920_000,             // 1 USDC = 0.920 EUR at deposit
    currentRate: 930_000,             // now 0.930
    depositTime: FOURTEEN_DAYS_AGO,
  },
  {
    currency: 'GBP',
    currencySymbol: '\u00A3',
    flag: '\u{1F1EC}\u{1F1E7}',
    localBalance: 397_500_000,        // GBP 397.50
    usdcBacking: 500_000_000,         // $500 USDC
    pendingYieldUsdc: 920_000,        // $0.92 USDC
    pendingYieldLocal: 731_400,       // GBP 0.73
    totalClaimedUsdc: 12_100_000,     // $12.10 USDC
    totalClaimedLocal: 9_620_000,     // GBP 9.62
    depositRate: 790_000,
    currentRate: 795_000,
    depositTime: SEVEN_DAYS_AGO,
  },
  {
    currency: 'JPY',
    currencySymbol: '\u00A5',
    flag: '\u{1F1EF}\u{1F1F5}',
    localBalance: 77_000_000_000,     // JPY 77,000
    usdcBacking: 500_000_000,         // $500 USDC
    pendingYieldUsdc: 2_100_000,      // $2.10 USDC
    pendingYieldLocal: 323_400_000,   // JPY 323
    totalClaimedUsdc: 18_500_000,     // $18.50 USDC
    totalClaimedLocal: 2_849_000_000, // JPY 2,849
    depositRate: 152_000_000,
    currentRate: 154_000_000,
    depositTime: THIRTY_DAYS_AGO,
  },
  {
    currency: 'MXN',
    currencySymbol: 'MX$',
    flag: '\u{1F1F2}\u{1F1FD}',
    localBalance: 4_375_000_000,      // MXN 4,375
    usdcBacking: 250_000_000,         // $250 USDC
    pendingYieldUsdc: 1_250_000,      // $1.25 USDC
    pendingYieldLocal: 21_875_000,    // MXN 21.88
    totalClaimedUsdc: 8_900_000,      // $8.90 USDC
    totalClaimedLocal: 155_750_000,   // MXN 155.75
    depositRate: 17_200_000,
    currentRate: 17_500_000,
    depositTime: FOURTEEN_DAYS_AGO,
  },
  {
    currency: 'BRL',
    currencySymbol: 'R$',
    flag: '\u{1F1E7}\u{1F1F7}',
    localBalance: 1_262_500_000,      // BRL 1,262.50
    usdcBacking: 250_000_000,         // $250 USDC
    pendingYieldUsdc: 680_000,        // $0.68 USDC
    pendingYieldLocal: 3_434_000,     // BRL 3.43
    totalClaimedUsdc: 5_300_000,      // $5.30 USDC
    totalClaimedLocal: 26_765_000,    // BRL 26.77
    depositRate: 4_980_000,
    currentRate: 5_050_000,
    depositTime: SEVEN_DAYS_AGO,
  },
  {
    currency: 'INR',
    currencySymbol: '\u20B9',
    flag: '\u{1F1EE}\u{1F1F3}',
    localBalance: 8_350_000_000,      // INR 8,350
    usdcBacking: 100_000_000,         // $100 USDC
    pendingYieldUsdc: 450_000,        // $0.45 USDC
    pendingYieldLocal: 37_575_000,    // INR 37.58
    totalClaimedUsdc: 3_200_000,      // $3.20 USDC
    totalClaimedLocal: 267_200_000,   // INR 267.20
    depositRate: 83_000_000,
    currentRate: 83_500_000,
    depositTime: FOURTEEN_DAYS_AGO,
  },
];
