import { Wallet, Currency, CurrencyRegion, Transaction } from './types';

// ---------------------------------------------------------------------------
// Testnet Configuration
// ---------------------------------------------------------------------------
export const RPC_URL = process.env.NEXT_PUBLIC_RPC_URL || 'http://35.184.213.248:8545';
export const REST_URL = process.env.NEXT_PUBLIC_REST_URL || 'http://35.184.213.248:8080';
export const CHAIN_ID = 'dina-testnet-1';

// ---------------------------------------------------------------------------
// Mock Wallets
// ---------------------------------------------------------------------------
const NOW = Math.floor(Date.now() / 1000);
const ONE_HOUR_AGO = NOW - 3600;
const ONE_DAY_AGO = NOW - 86400;
const THREE_DAYS_AGO = NOW - 259200;

export const MOCK_WALLETS: Wallet[] = [
  {
    id: 'main-1',
    name: 'Main Wallet',
    type: 'main',
    icon: '🏦',
    balance: 2_347_530_000,
    yieldRateBps: 450,
    lastYieldUpdate: ONE_HOUR_AGO,
    isDefault: true,
    isSetUp: true,
  },
  {
    id: 'savings-1',
    name: 'Savings',
    type: 'savings',
    icon: '🐷',
    balance: 10_000_000_000,
    yieldRateBps: 500,
    lastYieldUpdate: ONE_HOUR_AGO,
    isSetUp: true,
  },
  {
    id: 'backup-1',
    name: 'Backup',
    type: 'backup',
    icon: '🔒',
    balance: 500_000_000,
    yieldRateBps: 450,
    lastYieldUpdate: ONE_HOUR_AGO,
    isSetUp: true,
  },
  {
    id: 'agent-1',
    name: 'Shopping',
    type: 'agent',
    icon: '🛒',
    balance: 150_000_000,
    yieldRateBps: 350,
    lastYieldUpdate: ONE_HOUR_AGO,
    dailyLimit: 500_000_000,
    isSetUp: true,
  },
  {
    id: 'agent-2',
    name: 'Bills',
    type: 'agent',
    icon: '📄',
    balance: 50_000_000,
    yieldRateBps: 350,
    lastYieldUpdate: ONE_HOUR_AGO,
    dailyLimit: 200_000_000,
    isSetUp: true,
  },
  {
    id: 'agent-3',
    name: 'Agent 3',
    type: 'agent',
    icon: '🤖',
    balance: 0,
    yieldRateBps: 350,
    lastYieldUpdate: NOW,
    isSetUp: false,
  },
  {
    id: 'speed-1',
    name: 'Business',
    type: 'speed',
    icon: '⚡',
    balance: 100_000_000,
    yieldRateBps: 300,
    lastYieldUpdate: ONE_HOUR_AGO,
    isSetUp: true,
  },
  {
    id: 'speed-2',
    name: 'Speed 2',
    type: 'speed',
    icon: '⚡',
    balance: 0,
    yieldRateBps: 300,
    lastYieldUpdate: NOW,
    isSetUp: false,
  },
  {
    id: 'speed-3',
    name: 'Speed 3',
    type: 'speed',
    icon: '⚡',
    balance: 0,
    yieldRateBps: 300,
    lastYieldUpdate: NOW,
    isSetUp: false,
  },
];

// ---------------------------------------------------------------------------
// All 155 Deployed Currencies (from deploy-all-currencies.js)
// Rates are micro-units per 1 USDC (6 decimals). e.g. EUR at 0.93 = 930_000
// Yield rates in basis points (450 = 4.50% APY)
//
// Generated by: node scripts/deploy-all-currencies.js
// Source JSON:   wallet-app/src/lib/currencies.json
// ---------------------------------------------------------------------------
import deployedCurrencies from './currencies.json';

// Country code -> region mapping for display grouping
const COUNTRY_REGION_MAP: Record<string, CurrencyRegion> = {
  // Major (top-level global reserve currencies get special grouping)
  US: 'Major', EU: 'Major', GB: 'Major', JP: 'Major', CH: 'Major', AU: 'Major', CA: 'Major', CN: 'Major',
  // North America
  MX: 'North America', GT: 'North America', BZ: 'North America', HN: 'North America', NI: 'North America',
  CR: 'North America', PA: 'North America', DO: 'North America', CU: 'North America', HT: 'North America',
  JM: 'North America', TT: 'North America', BB: 'North America', BS: 'North America', EC: 'North America',
  AW: 'North America', CW: 'North America', BM: 'North America', KY: 'North America',
  // South America
  BR: 'South America', AR: 'South America', CL: 'South America', CO: 'South America', PE: 'South America',
  UY: 'South America', PY: 'South America', BO: 'South America', VE: 'South America', GY: 'South America',
  SR: 'South America', FK: 'South America',
  // Western Europe
  SE: 'Western Europe', NO: 'Western Europe', DK: 'Western Europe', IS: 'Western Europe', GI: 'Western Europe',
  // Eastern Europe
  PL: 'Eastern Europe', CZ: 'Eastern Europe', HU: 'Eastern Europe', RO: 'Eastern Europe', BG: 'Eastern Europe',
  HR: 'Eastern Europe', RS: 'Eastern Europe', BA: 'Eastern Europe', MK: 'Eastern Europe', AL: 'Eastern Europe',
  MD: 'Eastern Europe', UA: 'Eastern Europe', BY: 'Eastern Europe', GE: 'Eastern Europe', AM: 'Eastern Europe',
  AZ: 'Eastern Europe', TR: 'Eastern Europe', RU: 'Eastern Europe',
  // East Asia
  TW: 'East Asia', HK: 'East Asia', MO: 'East Asia', MN: 'East Asia', KP: 'East Asia', KR: 'East Asia',
  // Southeast Asia
  SG: 'Southeast Asia', TH: 'Southeast Asia', MY: 'Southeast Asia', ID: 'Southeast Asia', PH: 'Southeast Asia',
  VN: 'Southeast Asia', MM: 'Southeast Asia', KH: 'Southeast Asia', LA: 'Southeast Asia', BN: 'Southeast Asia',
  TL: 'Southeast Asia',
  // South Asia
  IN: 'South Asia', PK: 'South Asia', BD: 'South Asia', LK: 'South Asia', NP: 'South Asia',
  BT: 'South Asia', MV: 'South Asia', AF: 'South Asia',
  // Middle East
  AE: 'Middle East', SA: 'Middle East', QA: 'Middle East', BH: 'Middle East', OM: 'Middle East',
  KW: 'Middle East', JO: 'Middle East', IL: 'Middle East', LB: 'Middle East', IQ: 'Middle East',
  IR: 'Middle East', SY: 'Middle East', YE: 'Middle East',
  // Central Asia
  KZ: 'Central Asia', UZ: 'Central Asia', KG: 'Central Asia', TJ: 'Central Asia', TM: 'Central Asia',
  // North Africa
  EG: 'North Africa', MA: 'North Africa', DZ: 'North Africa', TN: 'North Africa', LY: 'North Africa', SD: 'North Africa',
  // West Africa
  NG: 'West Africa', GH: 'West Africa', WA: 'West Africa', GM: 'West Africa', GN: 'West Africa',
  SL: 'West Africa', LR: 'West Africa', CV: 'West Africa', MR: 'West Africa',
  // East Africa
  KE: 'East Africa', TZ: 'East Africa', UG: 'East Africa', ET: 'East Africa', RW: 'East Africa',
  BI: 'East Africa', SO: 'East Africa', DJ: 'East Africa', ER: 'East Africa', SS: 'East Africa',
  // Central Africa (XAF uses 'CA' country code which collides with Canada — handled below)
  CD: 'Central Africa', ST: 'Central Africa',
  // Southern Africa
  ZA: 'Southern Africa', BW: 'Southern Africa', NA: 'Southern Africa', SZ: 'Southern Africa',
  LS: 'Southern Africa', MW: 'Southern Africa', ZM: 'Southern Africa', MZ: 'Southern Africa',
  AO: 'Southern Africa', MG: 'Southern Africa', MU: 'Southern Africa', SC: 'Southern Africa',
  KM: 'Southern Africa', ZW: 'Southern Africa',
  // Oceania
  NZ: 'Oceania', FJ: 'Oceania', PG: 'Oceania', WS: 'Oceania', TO: 'Oceania',
  VU: 'Oceania', SB: 'Oceania', PF: 'Oceania',
};

// Special override: XAF's country is 'CA' (Central Africa) which collides with Canada
function getRegion(code: string, country: string): CurrencyRegion {
  if (code === 'XAF') return 'Central Africa';
  return COUNTRY_REGION_MAP[country] || 'Middle East & Africa';
}

// Build the full currency list from deployed data + USDC as native
export const MOCK_CURRENCIES: Currency[] = [
  // USDC is native — not in the deployed JSON
  { symbol: 'USDC', name: 'US Dollar', balance: 12_947_530_000, yieldRateBps: 450, ratePerUsdc: 1_000_000, icon: '\u{1F1FA}\u{1F1F8}', region: 'Major' },
  // All 154 deployed stablecoins
  ...deployedCurrencies.map((c: { symbol: string; name: string; yield: number; rate: number; flag: string; code: string; country: string }) => ({
    symbol: c.symbol,
    name: c.name,
    balance: 0,
    yieldRateBps: c.yield,
    ratePerUsdc: c.rate,
    icon: c.flag,
    region: getRegion(c.code, c.country),
  })),
];

// ---------------------------------------------------------------------------
// Currency region order for display grouping
// ---------------------------------------------------------------------------
export const CURRENCY_REGIONS = [
  'Major',
  'North America',
  'South America',
  'Western Europe',
  'Eastern Europe',
  'East Asia',
  'Southeast Asia',
  'South Asia',
  'Middle East',
  'Central Asia',
  'North Africa',
  'West Africa',
  'East Africa',
  'Central Africa',
  'Southern Africa',
  'Oceania',
] as const;

// ---------------------------------------------------------------------------
// Mock Transactions
// ---------------------------------------------------------------------------
export const MOCK_TRANSACTIONS: Transaction[] = [
  { id: 'tx-1', type: 'receive', amount: 500_000_000, currency: 'USDC', counterparty: 'alice.dina', timestamp: ONE_HOUR_AGO, status: 'confirmed', wallet: 'Main Wallet' },
  { id: 'tx-2', type: 'send', amount: 25_000_000, currency: 'USDC', counterparty: 'bob@email.com', timestamp: ONE_DAY_AGO, status: 'confirmed', wallet: 'Main Wallet' },
  { id: 'tx-3', type: 'yield', amount: 1_232_000, currency: 'USDC', timestamp: ONE_DAY_AGO, status: 'confirmed', wallet: 'Savings' },
  { id: 'tx-4', type: 'convert', amount: 200_000_000, currency: 'EURC', counterparty: 'USDC -> EURC', timestamp: THREE_DAYS_AGO, status: 'confirmed', wallet: 'Main Wallet' },
  { id: 'tx-5', type: 'send', amount: 75_000_000, currency: 'USDC', counterparty: 'carol.dina', timestamp: THREE_DAYS_AGO, status: 'confirmed', wallet: 'Shopping' },
];

export const MOCK_WALLET_ADDRESS = '0xd1nA...7f3E';
export const MOCK_WALLET_ADDRESS_FULL = '0xd1nA4b2c8E9f0A1B3d5C7e2F4a6D8b0E9c1F3a5D7f3E';
